display:
  model: Turing Smart Screen 3.5
  port: AUTO
  width: 480
  height: 320
  orientation: reverse_landscape
  brightness: 100
background:
  source: file
  path: assets/background.png
  folder: null
  slideshow_interval_minutes: 5
  mode: cover
  colour: '#02040a'
theme:
  name: Forged Core
  foreground: '#f4fbff'
  accent: '#27e7ff'
  panel: '#080d18'
widgets:
- kind: cpu_usage
  render_mode: circle
  enabled: true
  left_text: ''
  right_text: ''
  x: 14
  y: 16
  width: 112
  height: 112
  font: Segoe UI
  font_size: 30.0
  colour: '#00bfff'
  secondary_colour: '#78fff1'
  opacity: 0.95
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 7
  shadow: 5
  use_thresholds: true
  warning_threshold: 65.0
  critical_threshold: 90.0
  warning_colour: '#ffd447'
  critical_colour: '#ff315b'
  circle_thickness: 10.0
  circle_start_angle: -90.0
  circle_sweep_angle: 300.0
  refresh_interval_ms: 300
  label_format: '{value}'
- kind: text
  render_mode: text
  enabled: true
  left_text: ''
  right_text: ''
  x: 47
  y: 31
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 16.0
  colour: '#6eeeff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 3
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: CPU
- kind: cpu_usage
  render_mode: text
  enabled: true
  left_text: ''
  right_text: '%'
  x: 41
  y: 53
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 35.0
  colour: '#ffffff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 5
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: cpu_temperature
  render_mode: text
  enabled: true
  left_text: ''
  right_text: °
  x: 48
  y: 92
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 17.0
  colour: '#70fff1'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 3
  shadow: 0
  use_thresholds: true
  warning_threshold: 70.0
  critical_threshold: 88.0
  warning_colour: '#ffd447'
  critical_colour: '#ff315b'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: gpu_usage
  render_mode: circle
  enabled: true
  left_text: ''
  right_text: ''
  x: 354
  y: 16
  width: 112
  height: 112
  font: Segoe UI
  font_size: 30.0
  colour: '#b72cff'
  secondary_colour: '#ff3fcf'
  opacity: 0.95
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 7
  shadow: 5
  use_thresholds: true
  warning_threshold: 75.0
  critical_threshold: 95.0
  warning_colour: '#ff9f43'
  critical_colour: '#ff315b'
  circle_thickness: 10.0
  circle_start_angle: -90.0
  circle_sweep_angle: 300.0
  refresh_interval_ms: 300
  label_format: '{value}'
- kind: text
  render_mode: text
  enabled: true
  left_text: ''
  right_text: ''
  x: 389
  y: 31
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 16.0
  colour: '#ff67dd'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 3
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: GPU
- kind: gpu_usage
  render_mode: text
  enabled: true
  left_text: ''
  right_text: '%'
  x: 381
  y: 53
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 35.0
  colour: '#ffffff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 5
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: gpu_temperature
  render_mode: text
  enabled: true
  left_text: ''
  right_text: °
  x: 389
  y: 92
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 17.0
  colour: '#ff67dd'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 3
  shadow: 0
  use_thresholds: true
  warning_threshold: 70.0
  critical_threshold: 83.0
  warning_colour: '#ffd447'
  critical_colour: '#ff315b'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: clock
  render_mode: text
  enabled: true
  left_text: ''
  right_text: ''
  x: 175
  y: 13
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 34.0
  colour: '#ffffff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 6
  shadow: 4
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: date
  render_mode: text
  enabled: true
  left_text: ''
  right_text: ''
  x: 193
  y: 51
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 14.0
  colour: '#9fb7d5'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 2
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: gpu_power
  render_mode: text
  enabled: true
  left_text: 'GPU '
  right_text: ' W'
  x: 190
  y: 76
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 16.0
  colour: '#ff77de'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 3
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: volume
  render_mode: bar
  enabled: true
  left_text: ''
  right_text: ''
  x: 170
  y: 112
  width: 140
  height: 11
  font: Segoe UI
  font_size: 30.0
  colour: '#1979ff'
  secondary_colour: '#ff35dc'
  opacity: 0.9
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 5
  shadow: 3
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 100
  label_format: '{value}'
- kind: volume
  render_mode: text
  enabled: true
  left_text: 'VOL '
  right_text: '%'
  x: 207
  y: 95
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 13.0
  colour: '#dcecff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 2
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: cpu_temperature
  render_mode: bar
  enabled: true
  left_text: ''
  right_text: ''
  x: 18
  y: 148
  width: 210
  height: 12
  font: Segoe UI
  font_size: 30.0
  colour: '#00a8ff'
  secondary_colour: '#65fff1'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 4
  shadow: 0
  use_thresholds: true
  warning_threshold: 70.0
  critical_threshold: 88.0
  warning_colour: '#ffd447'
  critical_colour: '#ff315b'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 500
  label_format: '{value}'
- kind: text
  render_mode: text
  enabled: true
  left_text: ''
  right_text: ''
  x: 18
  y: 130
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 13.0
  colour: '#70eaff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 0
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: CPU TEMP
- kind: cpu_temperature
  render_mode: text
  enabled: true
  left_text: ''
  right_text: °C
  x: 184
  y: 128
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 15.0
  colour: '#ffffff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 0
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: gpu_temperature
  render_mode: bar
  enabled: true
  left_text: ''
  right_text: ''
  x: 252
  y: 148
  width: 210
  height: 12
  font: Segoe UI
  font_size: 30.0
  colour: '#7428ff'
  secondary_colour: '#ff35cf'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 4
  shadow: 0
  use_thresholds: true
  warning_threshold: 70.0
  critical_threshold: 83.0
  warning_colour: '#ffd447'
  critical_colour: '#ff315b'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 500
  label_format: '{value}'
- kind: text
  render_mode: text
  enabled: true
  left_text: ''
  right_text: ''
  x: 252
  y: 130
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 13.0
  colour: '#ff70dc'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 0
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: GPU TEMP
- kind: gpu_temperature
  render_mode: text
  enabled: true
  left_text: ''
  right_text: °C
  x: 418
  y: 128
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 15.0
  colour: '#ffffff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 0
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: cpu_clock
  render_mode: text
  enabled: true
  left_text: 'CPU '
  right_text: ''
  x: 18
  y: 165
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 15.0
  colour: '#b8f9ff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 2
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: gpu_clock
  render_mode: text
  enabled: true
  left_text: 'GPU '
  right_text: ''
  x: 385
  y: 166
  width: 87
  height: 22
  font: Bahnschrift
  font_size: 15.0
  colour: '#ffd0f5'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 2
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: ram_usage
  render_mode: bar
  enabled: true
  left_text: ''
  right_text: ''
  x: 18
  y: 207
  width: 140
  height: 12
  font: Segoe UI
  font_size: 30.0
  colour: '#00bfff'
  secondary_colour: '#72fff1'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 4
  shadow: 0
  use_thresholds: true
  warning_threshold: 75.0
  critical_threshold: 92.0
  warning_colour: '#ffd447'
  critical_colour: '#ff315b'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: ram_usage
  render_mode: text
  enabled: true
  left_text: 'RAM '
  right_text: '%'
  x: 18
  y: 187
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 15.0
  colour: '#dffcff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 0
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: vram_usage
  render_mode: bar
  enabled: true
  left_text: ''
  right_text: ''
  x: 322
  y: 207
  width: 140
  height: 12
  font: Segoe UI
  font_size: 30.0
  colour: '#762cff'
  secondary_colour: '#ff42d4'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 4
  shadow: 0
  use_thresholds: true
  warning_threshold: 75.0
  critical_threshold: 92.0
  warning_colour: '#ffd447'
  critical_colour: '#ff315b'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: vram_usage
  render_mode: text
  enabled: true
  left_text: 'VRAM '
  right_text: '%'
  x: 386
  y: 187
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 15.0
  colour: '#ffe0fa'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 0
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: network_download
  render_mode: graph
  enabled: true
  left_text: ''
  right_text: ''
  x: 18
  y: 242
  width: 145
  height: 61
  font: Segoe UI
  font_size: 30.0
  colour: '#00a8ff'
  secondary_colour: '#65fff1'
  opacity: 0.9
  graph_background_colour: '#020914'
  graph_background_opacity: 0.55
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 3
  shadow: 3
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 500
  label_format: '{value}'
- kind: network_download
  render_mode: text
  enabled: true
  left_text: 'NET ↓ '
  right_text: ' KB/s'
  x: 19
  y: 222
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 13.0
  colour: '#89f6ff'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 0
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
- kind: gpu_power
  render_mode: graph
  enabled: true
  left_text: ''
  right_text: ''
  x: 317
  y: 242
  width: 145
  height: 61
  font: Segoe UI
  font_size: 30.0
  colour: '#8d2cff'
  secondary_colour: '#ff42d4'
  opacity: 0.9
  graph_background_colour: '#100313'
  graph_background_opacity: 0.55
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 3
  shadow: 3
  use_thresholds: true
  warning_threshold: 250.0
  critical_threshold: 400.0
  warning_colour: '#ff9f43'
  critical_colour: '#ff315b'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 500
  label_format: '{value}'
- kind: gpu_power
  render_mode: text
  enabled: true
  left_text: 'POWER '
  right_text: ' W'
  x: 375
  y: 222
  width: 210
  height: 54
  font: Bahnschrift
  font_size: 13.0
  colour: '#ff9bea'
  secondary_colour: '#64d8cb'
  opacity: 1.0
  graph_background_colour: '#000000'
  graph_background_opacity: 0.0
  gif_path: null
  gif_fps: 8
  gif_loop: true
  gif_fit: contain
  glow: 0
  shadow: 0
  use_thresholds: false
  warning_threshold: 70.0
  critical_threshold: 90.0
  warning_colour: '#ffd166'
  critical_colour: '#ff4d6d'
  circle_thickness: 16.0
  circle_start_angle: -90.0
  circle_sweep_angle: 360.0
  refresh_interval_ms: 1000
  label_format: '{value}'
sensor_poll_ms: 500
frame_interval_ms: 100
libre_hardware_monitor_dll: null
cpu_temperature_source: core
cpu_clock_source: average
fan_sensor: null
automation:
  enabled: false
  default_screen: null
  rules: []
transition:
  kind: fade
  duration_ms: 450
